### ISSUE TITLE
What is the best strategy for compiling to common js?

### ISSUE THREAD

**Issue by simontegg** [tgdwyer/WebCola#104]
My fork makes substantial changes to the layout of the typescript files:
compare [simontegg](https://github.com/simontegg/WebCola/blob/master/WebCola/src/descent.ts) vs [tgdwyer](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/descent.ts). 

I followed this strategy to assist compiling to common js [module](https://github.com/simontegg/WebCola/blob/master/index.js), while keeping a [browser global version](https://github.com/simontegg/WebCola/blob/master/browser.js) to ensure the test suite passed.

My goal is to use WebCola in a node js server and in the browser independent of d3, and have the package available on npm. 

Unfortunately, as @aspiers has pointed out all these changes make it difficult for maintainers to assess and merge the fork. 

I don't know typescript. I am wondering what the best practice is for creating common js modules from typescript projects? If we can agree on this upfront I can put the time into executing the agreed strategy.

**Comment by tgdwyer** [comment]
Thanks for looking into this.  I'm keen to make webcola available to as many people, in as many different situations, as possible.  So if we have to make some widespread changes to achieve this I'm definitely open to it. Having said that, let's try to be careful.

TypeScript is currently a fast-moving target.  It looks like 1.5 has changed the module semantics somewhat:
https://github.com/Microsoft/TypeScript/issues/2242#issuecomment-83694181

I have no experience with CommonJS (one of the reasons I moved to TypeScript was precisely because javascript encapsulation workarounds were doing my head in).  

Do you think the new behaviour in TS1.5 will help you with CommonJS compatibility?  (I'm thinking of moving webcola to 1.5 soon)

**Comment by tgdwyer** [comment]
Here's a better article discussing TS1.5 and module support with commonjs:

https://github.com/Microsoft/TypeScript/wiki/Modules

**Comment by jnetterf** [comment]
I [gave adding CommonJS support a shot](https://github.com/tgdwyer/WebCola/pull/108) without making any structural changes.

TypeScript has both **internal** and **external** modules, and they don't get along very well. When you write `module blah { ... }`, or `reference` code that uses modules (with the exception of ambient/"declared" modules like in `.d.ts` files), you're using internal modules. When you're using `export` or `import`, you're using external modules. For CommonJS support, it's easier if you purely use external modules, but with some slight hacking, you can get CommonJS support without rewriting everything. That's the goal of my PR.

It doesn't look to me like the new behaviour (`export default`) helps with interop between external and internal modules, but I could be missing something.

**Comment by tgdwyer** [comment]
I've merged #108 - does this resolve the issue?  Is there anything else we should consider doing for better commonjs support?

**Comment by tgdwyer** [comment]
The pull-request from @jnetterf (now merged) was a pretty good compromise, and means we now support commonjs modules.  Closing this issue to clean up - if there is still a problem please reopen.
