### ISSUE TITLE
Transitioning in and out of constraints

### ISSUE THREAD

**Issue by shlomokraus** [tgdwyer/WebCola#161]
Hi, 

I am applying and disabling constraints following user interaction by calling 'force.constraints([]).start()'
with and without elements in the constraints array. 

Problem is, the layout is changed immediately after calling start(), without a nice transition, even if I pass values to start method (start(70,15,5));

Is there a way to transition in and out of constraints? 

Thanks

**Comment by tgdwyer** [comment]
Great question.

cola does not deliberately aim to provide smooth transitions, rather it is trying to optimise the goal function as quickly as possible.  It just so happens that usually the steps in the optimisation are fairly incremental and hence can look quite nice when animated.

Disabling constraints will lead to a large jump in subsequent iterations of layout simply because there is suddenly a lot more freedom to move nodes towards an unconstrained optimum position.

Adding parameters to the start method, by the way, will actually create larger jumps because those parameters are actually telling cola to apply the specified number of iterations before notifying the tick event.

If you really want smooth transitions then I would recommend using D3's transition capabilities to do nice easing.  Note to self that I should make a nice example of combining D3 transitions with a cola tick handler.  Or if anyone already has one then please let me know :-)
