### ISSUE TITLE
Node position is reset on start()

### ISSUE THREAD

**Issue by shlomokraus** [tgdwyer/WebCola#164]
Consider the following example: 
http://codepen.io/plonit7/pen/jqmXWw

Doublclicking a node will add another node to the graph by updating the nodes array and calling start().

Problem: if I drag the nodes and then doubleclick one of them, the new graph will appear at the old (original) position, instead of the position where it was last seen after dragging. 

Is that a bug? Is there a way to overcome it? 

Thanks

**Comment by saivan** [comment]
Hmm, this seems to be happening to me as well in my own tests. It seems to happen any time I call start, or add any nodes.

**Comment by tgdwyer** [comment]
Aha!  The old "handle disconnected" trap!
http://codepen.io/anon/pen/WwOoXa

The problem in your version was that by default, cola.start() packs disconnected components after the initial layout - starting from 0,0.  So everytime you added a node, it would carry on the layout from the latest positions, but then it would move everything back to 0,0 :-).

The fix is to set:
```
.handleDisconnected(false)
```

In the long term I should probably think about whether this is the correct default behaviour!!
