### ISSUE TITLE
Styling Nodes

### ISSUE THREAD

**Issue by Baudin999** [tgdwyer/WebCola#173]
Hi, I was wondering if there is a convenient tutorial on how to style Nodes using WebCola. I love the way I can define and interact with layouts and nodes/graphs but I'm searching for a way to create dynamic "designers" with differently styled nodes. Some should look like people, others should look like cards. All in all I just want a bit of control on how to render them.

Thank you for the any information possible.

**Comment by gordonwoodhull** [comment]
This is really a d3 question and I think it's outside the scope of WebCola. 

If you are not concerned with clipping the edges at the boundary of an arbitrary polygon, it should be pretty simple. Just insert the shapes you want instead of the boxes or ellipses used in most of the examples. And make sure the edge layer is below the node layer so the nodes will be drawn on top.

I've been building a wrapper library to encapsulate the difficult d3 stuff and link to crossfilter, called dc.graph.js. Right now it supports regular polygons and ellipses. The shape generation code starts here:
https://github.com/dc-js/dc.graph.js/blob/master/src/shape.js#L73

And it's called from here:
https://github.com/dc-js/dc.graph.js/blob/master/src/diagram.js#L922

Probably a bit more complex than you need, but I hope it helps anyway.

**Comment by tgdwyer** [comment]
Thanks Gordon!  Yes, the webcola layout functionality itself knows very little about the styling of nodes.  Rather, if you use avoidOverlaps or edge routing then it simply treats the nodes as rectangles - you need to specify the dimensions of your visuals with the width and height properties on nodes, but webcola doesn't care what's inside those bounding boxes.  You set up the node visuals with SVG using standard D3 data binding (as per the webcola examples).

**Comment by Baudin999** [comment]
Thank you for the information, really appreciate it!
