### ISSUE TITLE
specify starting position of nodes

### ISSUE THREAD

**Issue by ignorabilis** [tgdwyer/WebCola#244]
Hi, I'm trying to do something very similar to aspiers in this issue - #63 , but instead of dagre we have precalculated node positions. However initializing the x & y of the nodes does not seem to work and they just spawn in the center. Here is a [jsbin](https://jsbin.com/rejitej/5/edit?js,console,output) showing the issue. It simply tries to place two nodes in the upper left corner instead of in the center. This approach works with the original D3 force. Also if I don't start cola the nodes are rendered in the upper left corner. I think I'm setting up things properly so this should work.

**Comment by gordonwoodhull** [comment]
As far as I know, there is no concept of "position hints" in cola. You can either fix the positions or leave them unspecified.

I believe it works to fix the positions, run a couple iterations, then unfix them.

**Comment by ignorabilis** [comment]
As stated in the other issue by @tgdwyer providing the initial positions of the nodes should work and it should work in a similar to D3 way. In our code we are already using the initial positions in our D3 force simulation and it works properly. The same code is not working the way we expected with cola.

Using position fixed is a nice workaround, thanks for that.

**Comment by gordonwoodhull** [comment]
My guess is that the core algorithm works fine, but there is a bug in the API layer so that the coordinates don't get through. When I do incremental layout, I have to keep the engine around so that the internal coordinates are preserved, and I get good coordinate stability that way. I'd prefer to be able to build the engine from scratch and give position hints.

This year is looking better for research, so perhaps I can find some time to help debug this. No promises though.

**Comment by ignorabilis** [comment]
@gordonwoodhull - Yes, this makes sense, as I found the actual code which assigns the default values to width/2 & height/2 only if there is no preexisting value. 

Any help would be appreciated. If this is getting in our way and I have the time I might hop in and try to fix it myself.

**Comment by den1k** [comment]
@gordonwoodhull I'm also running into this issue. Anyway I can help make progress on this? I'm new to Cola.js and Typescript but it would be helpful to point out the parts of source code that contain the bug.

**Comment by gordonwoodhull** [comment]
Hi @den1k. I haven't had any time to look into this, sorry. 

However, given that the feature exists and is supposed to work (and in my experience, does work in the case where you just keep the layout engine around) perhaps it would be an easy contribution for someone who is handy with developer tools?

**Comment by gordonwoodhull** [comment]
Hi, @worldsayshi, what I mean is that, instead of calling `cola.d3adaptor()` to create a layout engine each time I do a new layout, if I just reuse the same object, then some internal state seems to get saved, and I get more stable layouts.

@tgdwyer has argued many places that this should not make a difference, and I believe him. Yet, it seems to produce more stable layouts for me.

The only caveat is that constraints seem to accumulate and then fail (including overlap constraints #166), so when I am using constraints I need to also use groups - see #160.

Really hope to contribute some fixes rather than these workarounds...

**Comment by worldsayshi** [comment]
I plan to try to debug this one. But I ran into some snags when building. After some trial and error I got it to build: https://github.com/tgdwyer/WebCola/pull/259

**Comment by worldsayshi** [comment]
The problem occurs when calling `separateOverlappingComponents` in `start()`. 

1. Removing either this line:
```
this._descent.x[0][i] = v.x, this._descent.x[1][i] = v.y;
```
2. or this line:
```
applyPacking(graphs, width, height, this._defaultNodeSize);
```
3. or entirely removing `put_nodes_to_right_positions` in `handledisconnected.ts`

... will solve the issue. But it will likely break some other feature. I can't see what the use case for `put_nodes_to_right_positions` is really. When I initially start the graph it *seems* that the correct offset is set without it. It seems that everything works fine without it.

**Comment by worldsayshi** [comment]
I created a pull request that should fix this issue by adding an additional optional perameter to start().
