### ISSUE TITLE
Support for D3 versions above 4

### ISSUE THREAD

**Issue by VijethKrishna** [tgdwyer/WebCola#304]
Is there any plan or work-in-progress for adding the support for D3 versions above 4? I am currently in a situation where I need to use this package with D3 v5. Any info is much appreciated.

**Comment by mattsrinc** [comment]
Maybe this should really be in top 5 next wanted features to implement.

It appears it should be easy to rewrite d3adaptor.ts and create additional d3v6adaptor.ts (no need for version 5, let's jump directly to D3.js version 6 due to API changes that will possibly stick for years).

Basically event handling needs to be changed, upgrading regular scripts from D3.js v4 and v5 is quite easy (after tens of scripts I've upgraded):

[https://observablehq.com/@d3/d3v6-migration-guide]
