### ISSUE TITLE
Broken example?

### ISSUE THREAD

**Issue by cpressey** [tgdwyer/WebCola#76]
Hello!  The example on this page:

http://marvl.infotech.monash.edu/webcola/examples/modifyinggraph.html

does not work for me (Firefox 35.0.1 on Ubuntu.)  The SVG is blank and the Javascript console says

    TypeError: force.links is not a function (3x) (modifyinggraph.html line 75)

I tried most of the other examples, and they seem fine.

To step back -- I'm working on a project where I'd like to display a directed, weighted graph on a web page -- about 25 nodes, and dynamically updated.  I came across WebCola, and it seems like it would be a really good fit for implementing this.  However, the learning curve seems... kind of steep, due to the scant documentation.  I have two really basic questions:

*   The docs say it "works well with d3.js and svg.js", but does it actually _require_ either of those libraries?  I couldn't find any examples that don't use d3.  I have no great need to use d3 in this project, and if it's possible to go without it I'd prefer that.
*   Is it currently possible to display labels on arcs?

If it is possible to go d3-less, I'd like to put together a very simple, bare-bones, "Hello, world"-level example, and if I succeed at that, I'd be happy to contribute it (to the repo or the wiki.)

Thanks!

**Comment by cpressey** [comment]
I'm guessing now that the answer to the d3 dependency question is that WebCola doesn't strictly require it, but if you're laying out a graph, you probably want _display_ it, and in order to display it, you need a display layer.  And d3 is a display layer that WebCola knows about.

**Comment by tgdwyer** [comment]
The [example](http://marvl.infotech.monash.edu/webcola/examples/modifyinggraph.html) should work now.  I checked in a fix for [adaptor.js](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/adaptor.js).  It turned out a recent refactor deviated from the d3 pattern such that the "on" function returned the wrong thing.

Regarding whether you "need" d3.js ... you shouldn't, but indeed, a minimal example is missing.  
d3 is used in most of the examples for creating the svg visuals and also for the d3 eventing system.
[adaptor.js](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/adaptor.js) was a little while ago [refactored](https://github.com/tgdwyer/WebCola/pull/41) by @maxkfranz into two separate functions: ```d3adaptor``` which wraps the d3 eventing system, and ```adaptor``` which is completely independent of d3.  The d3adaptor function is a very minimal amount of code which could easily be bypassed and replaced with a different mechanism.  

I do have an example of using cola layout without d3, which instead uses [three.js to render the graph in 3d](http://marvl.infotech.monash.edu/webcola/examples/3dLayout.html).  However, it predates the nice adaptor.js refactor, and so it finishes up reimplementing the layout set-up and iteration code from adaptor.js.

Anyway, your idea of creating a "bare-bones" example that uses only the ```adaptor``` function in [adaptor.js](https://github.com/tgdwyer/WebCola/blob/master/WebCola/src/adaptor.js) and hence has no dependency on d3 would be great.  Of course you would need some other mechanism to create and manipulate the visuals.  For example, you could manipulate the svg in the dom directly, or work with canvas, webgl, etc.

As for labels on arcs, there is no code in cola at the moment that cleverly places them.  A simple solution that might work well enough for you is simple to calculate the centre-point of the edges and place the labels there.  Ideally, I guess cola could do something smart to find a nice place for them, e.g. a position that doesn't overlap with other visuals.

**Comment by cpressey** [comment]
@tgdwyer Thanks for the information!

For my purposes, centering the label along the arc should be fairly simple and totally sufficient.  In fact, it might even be better in my case to depict the weight using the linewidth of the arc.  At any rate, it's not a real problem for me.

I should probably learn d3 at some point, but I do want to try dissecting the basic example that you've just fixed and rewriting it to make it work with raw SVG DOM manipulation in Javascript.  I'll let you know once I make any progress on it.
